### ISSUE TITLE
Todo list 

### ISSUE THREAD

**Issue by jessimk** [UBC-MDS/DSCI-532_Alex-Jesica_Bechdel-Test#16]
@pak-alex 

- [x] Writeup 1st Draft (_Jes_)
- [x] Writeup 2nd Draft & Edit (_Alex_)
- [x] Adding context and info about the Bechdel Test and Rotten Tomatoes (_Jes_)
- [x] Adding a code of conduct (_Jes_)
- [x] grouped bar chart for plot 2 (_Alex_)
- [x] for plot 3, having genres on x-axis with jitter and transparency and hover (if possible) (_Alex_)

Wishlist
- [x]  proportions vs absolute counts on Plot 1
- [x] exploring darker themes to add a cinema vibe
- [x] adjusting plot 1 font
- [x] adjusting plot 1 width
